### ISSUE TITLE
Use a .gitignore file to exclude your .idea directory

### ISSUE THREAD

**Issue by etiology** [yovimaar/Permaculture-Lab-Monitor#1]
Hello,

I just noticed that you pushed your `.idea` directory from [pycharm](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems) to your repo.  If you create a `.gitignore` file in your main directory you can add items that git shouldn't be keeping track of.

If you right click on the `.gitignore` file and choose `Add template...` you should add the `JetBrains` template along with any others like MacOSX so that you don't post your data to a public repo.

**Comment by yovimaar** [comment]
Ooops! Thank you for pointing it out
